# This is just a starter, it is incomplete and a work-in-progress
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: surly-deployment
spec:
  selector:
    matchLabels:
      app: surly
  replicas: 2
  template:
    metadata:
      labels:
        app: surly
    spec:
      containers:
        - name: surly
          image: caprica/surly
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management
          env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: surly-secret
                  key: awsAccessKey
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: surly-secret
                  key: awsSecretKey
            - name: DYNAMODB_HOST
              value: FIXME
